project:
  type: book

execute:
  freeze: auto

book:
  title: "Python for Spatial Data Analysis"
  subtitle: "Module GG3209 - Second Part"
  version: 2023.2
  cover-image: img/cover.png
  author: "Dr. Fernando Benitez-Paez"
  date: "2023/02/23"

  search: true
  page-navigation: true
  repo-url: https://github.com/mfbenitezp/PY4SA
  repo-actions: [issue]
  downloads: [pdf, epub]
  sharing: [twitter, linkedin]
  favicon: img/favico.ico
  twitter-card: true
  site-url: https://github.com/mfbenitezp/PY4SA
  
  sidebar:
    style: docked
    background: silver

  chapters:
    - index.qmd
    - intro.qmd
    - working_tab_data.qmd
    - working_spat_data.qmd
    - USL_Clustering.qmd
    - auxillary_data.qmd
    - references.qmd

bibliography: references.bib
highlight-style: pygments
format:
  html:
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrartcl
    toc: true
    number-sections: true
    colorlinks: true